name: MCTools
version: '1.3.0'
main: com.mctools.MCTools
api-version: '1.20'
description: Advanced shape generation and terrain brush tool for builders
authors: [PenguinStudios Development]
website: https://mcutils.net

softdepend:
  - WorldEdit

commands:
  mctools:
    description: Main command for shape generation
    usage: /<command> <shape> <block> [parameters...]
    aliases: [mct, shapes, /mctools, /mct, /shapes]
  mcbrush:
    description: Terrain brush with heightmap support
    usage: /<command> [subcommand]
    aliases: [mcb, brush, /mcbrush, /mcb]

permissions:
  mctools.*:
    description: All MCTools permissions
    default: op
    children:
      mctools.use: true
      mctools.shapes.*: true
      mctools.gradient: true
      mctools.admin: true
      mctools.brush: true
      mctools.path.*: true
  mctools.use:
    description: Basic usage permission
    default: true
  mctools.shapes.*:
    description: All shape permissions
    default: op
    children:
      mctools.shapes.circle: true
      mctools.shapes.square: true
      mctools.shapes.rectangle: true
      mctools.shapes.ellipse: true
      mctools.shapes.polygon: true
      mctools.shapes.sphere: true
      mctools.shapes.dome: true
      mctools.shapes.cylinder: true
      mctools.shapes.cone: true
      mctools.shapes.pyramid: true
      mctools.shapes.arch: true
      mctools.shapes.torus: true
      mctools.shapes.spiral: true
      mctools.shapes.helix: true
      mctools.shapes.star: true
      mctools.shapes.line: true
      mctools.shapes.wall: true
      mctools.shapes.tube: true
      mctools.shapes.capsule: true
      mctools.shapes.ellipsoid: true
      mctools.shapes.tree: true
  mctools.gradient:
    description: Use gradient shape commands
    default: true
  mctools.admin:
    description: Admin commands (reload, etc)
    default: op
  mctools.bypass.limit:
    description: Bypass block limit
    default: op
  mctools.center:
    description: Use /mct center
    default: op
  mctools.worldedit.cp:
    description: Use /mct cp (WorldEdit copy+paste)
    default: op
  mctools.brush:
    description: Use MCBrush terrain tool
    default: op
  mctools.path.*:
    description: All path tool permissions
    default: op
    children:
      mctools.path.use: true
      mctools.path.generate: true
      mctools.path.bypass.limit: true
  mctools.path.use:
    description: Use path selection tool, modes, settings, preview
    default: op
  mctools.path.generate:
    description: Generate path structures (road, bridge)
    default: op
  mctools.path.bypass.limit:
    description: Bypass path point/length limits
    default: op
