name: MCTools
version: '1.0.0'
main: com.mctools.MCTools
api-version: '1.20'
description: Advanced shape generation and terrain brush tool for builders
authors: [PenguinStudios Development]
website: https://mcutils.net

commands:
  mctools:
    description: Main command for shape generation
    usage: /<command> <shape> <block> [parameters...]
    aliases: [mct, shapes, /mctools, /mct, /shapes]
  mcbrush:
    description: Terrain brush with heightmap support
    usage: /<command> [subcommand]
    aliases: [mcb, brush, /mcbrush, /mcb]

permissions:
  mctools.*:
    description: All MCTools permissions
    default: op
    children:
      mctools.use: true
      mctools.shapes.*: true
      mctools.gradient: true
      mctools.admin: true
      mctools.brush: true
  mctools.use:
    description: Basic usage permission
    default: true
  mctools.shapes.*:
    description: All shape permissions
    default: op
    children:
      mctools.shapes.circle: true
      mctools.shapes.square: true
      mctools.shapes.rectangle: true
      mctools.shapes.ellipse: true
      mctools.shapes.polygon: true
      mctools.shapes.sphere: true
      mctools.shapes.dome: true
      mctools.shapes.cylinder: true
      mctools.shapes.cone: true
      mctools.shapes.pyramid: true
      mctools.shapes.arch: true
      mctools.shapes.torus: true
      mctools.shapes.spiral: true
      mctools.shapes.helix: true
      mctools.shapes.star: true
      mctools.shapes.line: true
      mctools.shapes.wall: true
  mctools.gradient:
    description: Use gradient shape commands
    default: true
  mctools.admin:
    description: Admin commands (reload, etc)
    default: op
  mctools.bypass.limit:
    description: Bypass block limit
    default: op
  mctools.brush:
    description: Use MCBrush terrain tool
    default: op
